version: '3.8'

services:
  api-user:
    build:
      context: .
      dockerfile: user/Dockerfile
    container_name: api-user
    restart: unless-stopped
    environment:  
      TZ: Asia/Bangkok
    ports:
      - "8000:8000"
    volumes:
      - ./user:/app/user
      - ./core:/app/core
    networks:
      - project-net

  api-data:
    build:
      context: .
      dockerfile: data/Dockerfile
    container_name: api-data
    restart: unless-stopped
    environment:  
      TZ: Asia/Bangkok
    ports:
      - "8010:8010"
    volumes:
      - ./data:/app/data
      - ./core:/app/core
    networks:
      - project-net
  
  api-chat:
    build:
      context: .
      dockerfile: chat/Dockerfile
    container_name: api-chat
    restart: unless-stopped
    environment:  
      TZ: Asia/Bangkok
    ports:
      - "8020:8020"
    volumes:
      - ./chat:/app/chat
      - ./core:/app/core
      - ./response:/app/response
    networks:
      - project-net

  api-dashboard:
    build:
      context: .
      dockerfile: dashboard/Dockerfile
    container_name: api-dashboard
    restart: unless-stopped
    environment:  
      TZ: Asia/Bangkok
    ports:
      - "8030:8030"
    volumes:
      - ./dashboard:/app/dashboard
      - ./core:/app/core
    networks:
      - project-net

networks:
  project-net:
    external: true
  