version: '3.8'

services:
  api-user:
    build:
      context: .
      dockerfile: user/Dockerfile
    container_name: api-user
    restart: unless-stopped
    environment:  
      TZ: Asia/Bangkok
    ports:
      - "8000:8000"
    volumes:
      - /home/ecpai/storage/section-api/user/user:/app/user/user
      - /home/ecpai/storage/section-api/user/core:/app/user/core

  api-data:
    build:
      context: .
      dockerfile: data/Dockerfile
    container_name: api-data
    restart: unless-stopped
    environment:  
      TZ: Asia/Bangkok
    ports:
      - "8010:8010"
    volumes:
      - /home/ecpai/storage/section-api/data/data:/app/data/data
      - /home/ecpai/storage/section-api/data/core:/app/data/core
  
  api-chat:
    build:
      context: .
      dockerfile: chat/Dockerfile
    container_name: api-chat
    restart: unless-stopped
    environment:  
      TZ: Asia/Bangkok
    ports:
      - "8020:8020"
    volumes:
      - /home/ecpai/storage/section-api/chat/chat:/app/chat/chat
      - /home/ecpai/storage/section-api/chat/core:/app/chat/core
      - /home/ecpai/storage/section-api/chat/response:/app/chat/response

  api-dashboard:
    build:
      context: .
      dockerfile: dashboard/Dockerfile
    container_name: api-dashboard
    restart: unless-stopped
    environment:  
      TZ: Asia/Bangkok
    ports:
      - "8030:8030"
    volumes:
      - /home/ecpai/storage/section-api/dashboard/dashboard:/app/dashboard/dashboard
      - /home/ecpai/storage/section-api/dashboard/core:/app/dashboard/core